version: '3.8'

services:

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - docker-network
    volumes:
      - wordpress-website:/var/www/html
    depends_on:
      - wordpress
    ports:
      - "443:443"

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    restart: unless-stopped
    env_file:
      - .env
    volumes:
     - wordpress-website:/var/www/html
    networks:
      - docker-network
    depends_on:
      - mariadb

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    restart: unless-stopped
    volumes:
      - wordpress-db:/var/lib/mysql
    networks: 
      - docker-network
    env_file:
      - .env
  
volumes:
    wordpress-db:
      name: wordpress-db
      driver: local
      driver_opts:
              device: /home/lrosch/inception-volume/mariadb
              o: bind
              type: none

    wordpress-website:
      name: wordpress-website
      driver: local
      driver_opts:
              device: /home/lrosch/inception-volume/wordpress
              o: bind
              type: none
networks:
    docker-network:
      driver: bridge
